# Generated by Django 4.0.5 on 2023-01-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_bill_bill_alter_bill_dues_alter_bill_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='room',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
