# Generated by Django 4.0.5 on 2023-01-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_bill_bill_alter_bill_dues_alter_bill_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
