# Generated by Django 4.0.5 on 2023-07-05 12:50

from django.db import migrations


def copy_data(apps, schema_editor):
    MessBill = apps.get_model('backend', 'Bill')
    for bill in MessBill.objects.all():
        bill.year_temp = bill.year
        bill.month_temp = bill.month
        bill.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_messbill_month_temp_remove_messbill_year_temp_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]
