# Generated by Django 4.0.5 on 2023-07-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20230705_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='month',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='year',
        ),
        migrations.AddField(
            model_name='bill',
            name='month_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='year_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
