# Generated by Django 4.0.5 on 2023-07-05 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_bill_month_remove_bill_year_bill_month_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='month_temp',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='year_temp',
        ),
        migrations.AddField(
            model_name='bill',
            name='month',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='bill',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
