# Generated by Django 4.0.5 on 2023-07-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_bill_month_temp_remove_bill_year_temp_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='messbill',
            unique_together={('year', 'month')},
        ),
    ]
