# Generated by Django 4.0.5 on 2023-07-15 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_payingbill_current_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='payingbill',
            name='for_month',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
