# Generated by Django 4.0.5 on 2023-07-16 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_payingbill_for_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payingbill',
            name='for_month',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
