# Generated by Django 4.0.5 on 2023-07-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_payingbill_for_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
    ]
