# Generated by Django 4.0.5 on 2023-07-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_user_security'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='security',
            new_name='security_fee',
        ),
    ]
