# Generated by Django 4.0.5 on 2023-07-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_rename_security_user_security_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='grocery_and_other_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='meat_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='vegetable_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
