# Generated by Django 4.0.5 on 2023-07-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_expense_grocery_and_other_expenses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='grocery_and_other_expenses',
            new_name='expenses_expenses',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='meat_expenses',
            new_name='expenses_grocery_and_other',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='vegetable_expenses',
            new_name='expenses_meat',
        ),
    ]
