# Generated by Django 4.0.5 on 2023-07-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_rename_expenses_expenses_expense_expenses_vegetables'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total_attendances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
