# Generated by Django 4.0.5 on 2023-07-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_bill_total_attendances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='first_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='second_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='attendance_first_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='attendance_second_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_attendances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
