export const ADD_EXPENSES_REQUEST = 'ADD_EXPENSES_REQUEST'
export const ADD_EXPENSES_SUCCESS = 'ADD_EXPENSES_SUCCESS'
export const ADD_EXPENSES_FAIL = 'USER_LOGIN_FAIL'


export const GET_BILL_REQUEST = "GET_BILL_REQUEST"
export const GET_BILL_sUCCESS = "GET_BILL_SUCCESS"
export const GET_BILL_FAIL = "GET_BILL_FAIL" 