export const POST_ATTENDANCE_REQUEST = 'POST_ATTENDANCE_REQUEST'
export const POST_ATTENDANCE_SUCCESS = 'POST_ATTENDANCE_SUCCESS'
export const POST_ATTENDANCE_FAIL = 'POST_ATTENDANCE_FAIL'


export const GET_ATTENDANCE_REQUEST = 'GET_ATTENDANCE_REQUEST'
export const GET_ATTENDANCE_SUCCESS = 'GET_ATTENDANCE_SUCCESS'
export const GET_ATTENDANCE_FAIL = 'GET_ATTENDANCE_FAIL'


