export const ADD_EXPENSES_REQUEST = 'ADD_EXPENSES_REQUEST'
export const ADD_EXPENSES_SUCCESS = 'ADD_EXPENSES_SUCCESS'
export const ADD_EXPENSES_FAIL = 'ADD_EXPENSES_FAIL'

export const GET_EXPENSES_PER_MONTH_REQUEST = 'GET_EXPENSES_PER_MONTH_REQUEST'
export const GET_EXPENSES_PER_MONTH_SUCCESS = 'GET_EXPENSES_PER_MONTH_SUCCESS'
export const GET_EXPENSES_PER_MONTH_FAIL = 'GET_EXPENSES_PER_MONTH_FAIL'


export const GET_BILL_REQUEST = "GET_BILL_REQUEST"
export const GET_BILL_sUCCESS = "GET_BILL_SUCCESS"
export const GET_BILL_FAIL = "GET_BILL_FAIL"


export const ADD_BILL_REQUEST = 'POST_ADD_BILL_REQUEST'
export const ADD_BILL_success = 'POST_ADD_BILL_SUCCESS'
export const ADD_BILL_FAIL = 'POST_ADD_BILL_FAIL'