export const GET_MESS_MENU_REQUEST = 'GET_MESS_MENU_REQUEST'
export const GET_MESS_MENU_SUCCESS = 'GET_MESS_MENU_SUCCESS'
export const GET_MESS_MENU_FAIL = 'GET_MESS_MENU_FAIL'


export const UPDATE_MESS_MENU_REQUEST = 'UPDATE_MESS_MENU_REQUEST'
export const UPDATE_MESS_MENU_SUCCESS = 'UPDATE_MESS_MENU_SUCCESS'
export const UPDATE_MESS_MENU_FAIL = 'UPDATE_MESS_MENU_FAIL'
export const UPDATE_MESS_MENU_RESET = 'UPDATE_MESS_MENU_RESET'
