# Generated by Django 4.0.5 on 2022-06-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='studant',
        ),
    ]
