# Generated by Django 4.0.5 on 2022-06-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_menu_time_remove_user_city_remove_user_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
    ]
