# Generated by Django 4.0.5 on 2022-06-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_student_attendance_studant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_attendances', models.IntegerField(blank=True, null=True)),
                ('expenenses_per_capita', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='first_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='second_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
