# Generated by Django 4.0.5 on 2022-06-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('double', 'double')], default='present', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.CharField(choices=[('first_time', 'first_time'), ('second_time', 'second_time')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, null=True, unique=True),
        ),
    ]
