# Generated by Django 4.0.5 on 2022-06-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_expense_alter_menu_first_time_alter_menu_second_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expenenses_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_attendances',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
