# Generated by Django 4.0.5 on 2022-06-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_attendance_status_alter_attendance_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='status',
            new_name='first_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='second_time',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('double', 'double')], default='present', max_length=20, unique=True),
        ),
    ]
