# Generated by Django 4.0.5 on 2022-06-30 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_expense_expenenses_per_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expenenses_per_capita',
            new_name='expenses_per_capita',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='expenenses_per_day',
            new_name='expenses_per_day',
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.IntegerField(blank=True, null=True)),
                ('studant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
