# Generated by Django 4.0.5 on 2022-06-30 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_expenenses_per_capita_expense_expenses_per_capita_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='studant',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='studant',
        ),
        migrations.AddField(
            model_name='bill',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expenses_per_capita',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expenses_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_attendances',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
    ]
