# Generated by Django 4.0.5 on 2022-06-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_studant_attendance_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expenses_per_capita',
            new_name='expenses_per_attendance',
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_attendances',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
