# Generated by Django 4.0.5 on 2022-07-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_expenses_per_capita_expense_expenses_per_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='total_attendances',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
