# Generated by Django 4.0.5 on 2022-07-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_expense_total_attendances'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='month',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
