# Generated by Django 4.0.5 on 2022-07-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_bill_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
